x=input("Enter first number:")
y=input("Enter second number:")
sum=int(x)+int(y)
x=int(sum)-int(x)
print("First number after swaping:")
print(x)
y=int(sum)-int(y)
print("Second number after swaping:")
print(y)
